# Generated by Django 3.2.5 on 2022-09-10 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=50)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TweetPost',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('content_text', models.CharField(max_length=500)),
                ('img_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RelWordInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.tweetpost')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.keyword')),
            ],
        ),
    ]
