# Generated by Django 3.2.5 on 2022-09-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweetpost',
            name='num_char',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetpost',
            name='num_sentence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tweetpost',
            name='num_word',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
