# Generated by Django 3.2.5 on 2022-09-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_tweetpost_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='relwordinpost',
            name='hashtag',
            field=models.BooleanField(default=False),
        ),
    ]
