# Generated by Django 3.2.5 on 2022-09-19 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_relwordinpost_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PubMedPost',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('abstract', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=200)),
                ('num_word', models.IntegerField(default=0)),
                ('num_char', models.IntegerField(default=0)),
                ('num_sentence', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MedAuthor',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.pubmedpost')),
            ],
        ),
    ]
