# Generated by Django 3.2.5 on 2022-09-19 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_medauthor_pubmedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubmedpost',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='RelWordInMed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.pubmedpost')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.keyword')),
            ],
        ),
    ]
